### ISSUE TITLE
Lesson 4 Chapter Coordinated Motion Sample

### ISSUE THREAD

**Issue by jschamburger** [udacity/ud862-samples#3]
Hi,
not sure if I'm just blind, but I cannot find the sample for Lesson 4 Chapter Coordinated Motion. It is mentioned in the video, but the instructor notes only link to the Github project, not to a specific directory, and I wasn't able to find it among all the samples.
Could you please check this?

Thanks a lot!
Johannes

**Comment by 13rac1** [comment]
It is here: https://github.com/udacity/ud862-samples/tree/master/CoordinatedMotion

**Comment by jschamburger** [comment]
Thank you very much! Apparently it was added 15 days ago, so at least I wasn't blind when I looked for it on the first of October. ;-)

**Comment by 13rac1** [comment]
Haha, nope. It's a recent addition
