### ISSUE TITLE
local.properties in git repo

### ISSUE THREAD

**Issue by patrick-elmquist** [udacity/ud862-samples#4]
Hi,

you should probably remove the local.properties file in ud862-samples/SimplePaperTransformations

/Patrick

**Comment by jwill** [comment]
Fixed.

**Comment by druelle-mobile** [comment]
Fixed, but in fact, it appears that some of us have issues because of the missing local.properties .

> SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable. 

Could be fixed with a copy/paste of one of our personnal local.properties to the root of each project.
